// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (organization_id, user_id, action, resource, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, user_id, action, resource, details, ip_address, created_at
`

type CreateAuditLogParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Action         string
	Resource       string
	Details        []byte
	IpAddress      pgtype.Text
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.OrganizationID,
		arg.UserID,
		arg.Action,
		arg.Resource,
		arg.Details,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Action,
		&i.Resource,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByOrg = `-- name: ListAuditLogsByOrg :many
SELECT id, organization_id, user_id, action, resource, details, ip_address, created_at
FROM audit_logs
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Action,
			&i.Resource,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
