// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	ListAuditLogsByOrg(ctx context.Context, organizationID pgtype.UUID) ([]AuditLog, error)
}

var _ Querier = (*Queries)(nil)
