// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
}

var _ Querier = (*Queries)(nil)
