// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addUserToOrganization = `-- name: AddUserToOrganization :exec
INSERT INTO organization_members (organization_id, user_id)
VALUES ($1, $2)
`

type AddUserToOrganizationParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) error {
	_, err := q.db.Exec(ctx, addUserToOrganization, arg.OrganizationID, arg.UserID)
	return err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationUnit = `-- name: CreateOrganizationUnit :one
INSERT INTO organization_units (organization_id, name)
VALUES ($1, $2)
RETURNING id, organization_id, name, created_at
`

type CreateOrganizationUnitParams struct {
	OrganizationID uuid.UUID
	Name           string
}

func (q *Queries) CreateOrganizationUnit(ctx context.Context, arg CreateOrganizationUnitParams) (OrganizationUnit, error) {
	row := q.db.QueryRow(ctx, createOrganizationUnit, arg.OrganizationID, arg.Name)
	var i OrganizationUnit
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, created_at, updated_at
FROM organizations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationUnits = `-- name: ListOrganizationUnits :many
SELECT id, organization_id, name, created_at
FROM organization_units
WHERE organization_id = $1
ORDER BY name
`

func (q *Queries) ListOrganizationUnits(ctx context.Context, organizationID uuid.UUID) ([]OrganizationUnit, error) {
	rows, err := q.db.Query(ctx, listOrganizationUnits, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationUnit
	for rows.Next() {
		var i OrganizationUnit
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
