// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOrganizationUnit(ctx context.Context, arg CreateOrganizationUnitParams) (OrganizationUnit, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	ListOrganizationUnits(ctx context.Context, organizationID uuid.UUID) ([]OrganizationUnit, error)
}

var _ Querier = (*Queries)(nil)
