// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID             uuid.UUID
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	Action         string
	Resource       string
	Details        []byte
	IpAddress      pgtype.Text
	CreatedAt      time.Time
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrganizationMember struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	JoinedAt       time.Time
	RoleID         pgtype.UUID
}

type OrganizationUnit struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	CreatedAt      time.Time
}

type PasswordReset struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	Used      bool
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Permission struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

type Role struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
	CreatedAt      time.Time
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type Session struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	RefreshToken string
	UserAgent    pgtype.Text
	IpAddress    pgtype.Text
	IsRevoked    bool
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
