// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToMember = `-- name: AssignRoleToMember :exec
UPDATE organization_members
SET role_id = $1
WHERE organization_id = $2 AND user_id = $3
`

type AssignRoleToMemberParams struct {
	RoleID         pgtype.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) error {
	_, err := q.db.Exec(ctx, assignRoleToMember, arg.RoleID, arg.OrganizationID, arg.UserID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (organization_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, organization_id, name, description, created_at
`

type CreateRoleParams struct {
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.OrganizationID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
