// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) error
	CreatePermission(ctx context.Context, name string) (CreatePermissionRow, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
}

var _ Querier = (*Queries)(nil)
