// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
`

type AssignPermissionToRoleParams struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignRoleToMember = `-- name: AssignRoleToMember :exec
UPDATE organization_members
SET role_id = $1
WHERE organization_id = $2 AND user_id = $3
`

type AssignRoleToMemberParams struct {
	RoleID         pgtype.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) error {
	_, err := q.db.Exec(ctx, assignRoleToMember, arg.RoleID, arg.OrganizationID, arg.UserID)
	return err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (name)
VALUES ($1)
RETURNING id, name
`

type CreatePermissionRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreatePermission(ctx context.Context, name string) (CreatePermissionRow, error) {
	row := q.db.QueryRow(ctx, createPermission, name)
	var i CreatePermissionRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (organization_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, organization_id, name, description, created_at
`

type CreateRoleParams struct {
	OrganizationID uuid.UUID
	Name           string
	Description    pgtype.Text
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.OrganizationID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
