// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
}

var _ Querier = (*Queries)(nil)
