// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, used, expires_at, created_at
`

type CreatePasswordResetParams struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, refresh_token, is_revoked, expires_at, created_at
`

type CreateSessionParams struct {
	UserID       uuid.UUID
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	RefreshToken string
	IsRevoked    bool
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshToken, arg.ExpiresAt)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT id, user_id, token, used, expires_at, created_at
FROM password_resets
WHERE token = $1 LIMIT 1
`

func (q *Queries) GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByToken, token)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, refresh_token, is_revoked, expires_at, created_at
FROM sessions
WHERE refresh_token = $1 LIMIT 1
`

type GetSessionByTokenRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	RefreshToken string
	IsRevoked    bool
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetSessionByToken(ctx context.Context, refreshToken string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, refreshToken)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets
SET used = TRUE
WHERE id = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, id)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET is_revoked = TRUE
WHERE user_id = $1
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET is_revoked = TRUE
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}
