// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error)
	GetSessionByToken(ctx context.Context, refreshToken string) (GetSessionByTokenRow, error)
	MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
